# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1313, 754)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(0)
        self.splitter.setObjectName("splitter")
        self.menu_wg = QtWidgets.QWidget(self.splitter)
        self.menu_wg.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menu_wg.setFont(font)
        self.menu_wg.setStyleSheet("background-color:#06162d;\n"
"color:#fff;\n"
"border:none;")
        self.menu_wg.setObjectName("menu_wg")
        self.gridLayout = QtWidgets.QGridLayout(self.menu_wg)
        self.gridLayout.setContentsMargins(4, 4, 4, 15)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(self.menu_wg)
        self.toolBox.setStyleSheet("#toolBox {\n"
"    color: #fff;\n"
"}\n"
"\n"
"#toolBox::tab {\n"
"    padding-left:5px;\n"
"    text-align:left;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"\n"
"#toolBox::tab:selected {\n"
"    background-color: #2d9cdb;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#toolBox QPushButton {\n"
"    padding:5px 0px 5px 20px;\n"
"    text-align:left;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"#toolBox QPushButton:hover {\n"
"    background-color: #85C1E9;\n"
"}\n"
"\n"
"#toolBox QPushButton:checked {\n"
"    background-color: #3498DB;\n"
"}\n"
"\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.page1 = QtWidgets.QWidget()
        self.page1.setGeometry(QtCore.QRect(0, 0, 397, 223))
        self.page1.setObjectName("page1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page1)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.new_project_btn = QtWidgets.QPushButton(self.page1)
        self.new_project_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.new_project_btn.setCheckable(False)
        self.new_project_btn.setObjectName("new_project_btn")
        self.verticalLayout.addWidget(self.new_project_btn)
        self.new_concept_btn = QtWidgets.QPushButton(self.page1)
        self.new_concept_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.new_concept_btn.setCheckable(False)
        self.new_concept_btn.setObjectName("new_concept_btn")
        self.verticalLayout.addWidget(self.new_concept_btn)
        self.new_role_btn = QtWidgets.QPushButton(self.page1)
        self.new_role_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.new_role_btn.setCheckable(False)
        self.new_role_btn.setObjectName("new_role_btn")
        self.verticalLayout.addWidget(self.new_role_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons/new-badge-2-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page1, icon1, "")
        self.page2 = QtWidgets.QWidget()
        self.page2.setGeometry(QtCore.QRect(0, 0, 397, 223))
        self.page2.setObjectName("page2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page2)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.open_project_btn = QtWidgets.QPushButton(self.page2)
        self.open_project_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.open_project_btn.setCheckable(False)
        self.open_project_btn.setObjectName("open_project_btn")
        self.verticalLayout_2.addWidget(self.open_project_btn)
        self.open_concept_btn = QtWidgets.QPushButton(self.page2)
        self.open_concept_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.open_concept_btn.setCheckable(False)
        self.open_concept_btn.setObjectName("open_concept_btn")
        self.verticalLayout_2.addWidget(self.open_concept_btn)
        self.open_role_btn = QtWidgets.QPushButton(self.page2)
        self.open_role_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.open_role_btn.setCheckable(False)
        self.open_role_btn.setObjectName("open_role_btn")
        self.verticalLayout_2.addWidget(self.open_role_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons/open-in-browser-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page2, icon2, "")
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page3)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.run_project_btn = QtWidgets.QPushButton(self.page3)
        self.run_project_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.run_project_btn.setCheckable(True)
        self.run_project_btn.setObjectName("run_project_btn")
        self.verticalLayout_3.addWidget(self.run_project_btn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 174, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons/code-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page3, icon3, "")
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page4)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.save_project_btn = QtWidgets.QPushButton(self.page4)
        self.save_project_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.save_project_btn.setCheckable(False)
        self.save_project_btn.setObjectName("save_project_btn")
        self.verticalLayout_4.addWidget(self.save_project_btn)
        self.save_concept_btn = QtWidgets.QPushButton(self.page4)
        self.save_concept_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.save_concept_btn.setCheckable(False)
        self.save_concept_btn.setObjectName("save_concept_btn")
        self.verticalLayout_4.addWidget(self.save_concept_btn)
        self.save_role_btn = QtWidgets.QPushButton(self.page4)
        self.save_role_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.save_role_btn.setCheckable(False)
        self.save_role_btn.setObjectName("save_role_btn")
        self.verticalLayout_4.addWidget(self.save_role_btn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons/save-as-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page4, icon4, "")
        self.gridLayout.addWidget(self.toolBox, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 1, 1, 1)
        self.exit_btn = QtWidgets.QPushButton(self.menu_wg)
        self.exit_btn.setMinimumSize(QtCore.QSize(150, 50))
        self.exit_btn.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("#QPushButton {\n"
"    padding:5px 0px 5px 20px;\n"
"    text-align:left;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"   background-color:#85C1E9;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icons/x-mark-4-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon5)
        self.exit_btn.setCheckable(False)
        self.exit_btn.setChecked(False)
        self.exit_btn.setObjectName("exit_btn")
        self.gridLayout.addWidget(self.exit_btn, 2, 1, 1, 1)
        self.main_wg = QtWidgets.QWidget(self.splitter)
        self.main_wg.setObjectName("main_wg")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_wg)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.search_widget = QtWidgets.QWidget(self.main_wg)
        self.search_widget.setStyleSheet("#search_widget {background-color: #ABB2B9;}")
        self.search_widget.setObjectName("search_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.search_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.search_widget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_11.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_11.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Icons/arrow-96-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon6)
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_2.addWidget(self.pushButton_11)
        spacerItem5 = QtWidgets.QSpacerItem(241, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.search_frame = QtWidgets.QFrame(self.search_widget)
        self.search_frame.setMinimumSize(QtCore.QSize(300, 0))
        self.search_frame.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.search_frame.setFont(font)
        self.search_frame.setStyleSheet("#search_frame {\n"
"    border:  1px solid #aa7e6f;\n"
"    border-radius: 15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#search_btn {\n"
"    padding:5px 5px;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"#search_btn:pressed {\n"
"    padding-left: 10px;\n"
"}")
        self.search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_frame.setObjectName("search_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.search_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wellcome_lbl = QtWidgets.QLabel(self.search_frame)
        font = QtGui.QFont()
        font.setFamily("Harlow Solid Italic")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.wellcome_lbl.setFont(font)
        self.wellcome_lbl.setObjectName("wellcome_lbl")
        self.horizontalLayout.addWidget(self.wellcome_lbl)
        self.horizontalLayout_2.addWidget(self.search_frame)
        spacerItem6 = QtWidgets.QSpacerItem(241, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.user_label = QtWidgets.QLabel(self.search_widget)
        self.user_label.setMinimumSize(QtCore.QSize(30, 30))
        self.user_label.setMaximumSize(QtCore.QSize(30, 30))
        self.user_label.setStyleSheet("#user_label {\n"
"    background-color: #fff;\n"
"    border: 1px solid #F2F4F4;\n"
"    padding: 5px 5px;\n"
"    border-radius: 15%;\n"
"}")
        self.user_label.setText("")
        self.user_label.setPixmap(QtGui.QPixmap(":/icons/Icons/user-48.ico"))
        self.user_label.setScaledContents(True)
        self.user_label.setObjectName("user_label")
        self.horizontalLayout_2.addWidget(self.user_label)
        self.gridLayout_2.addWidget(self.search_widget, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.main_wg)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.pushButton_11.toggled['bool'].connect(self.menu_wg.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MiniKrol"))
        self.new_project_btn.setText(_translate("MainWindow", "Project"))
        self.new_concept_btn.setText(_translate("MainWindow", "Concept"))
        self.new_role_btn.setText(_translate("MainWindow", "Role"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page1), _translate("MainWindow", "New"))
        self.open_project_btn.setText(_translate("MainWindow", "Project"))
        self.open_concept_btn.setText(_translate("MainWindow", "Concept"))
        self.open_role_btn.setText(_translate("MainWindow", "Role"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page2), _translate("MainWindow", "open"))
        self.run_project_btn.setText(_translate("MainWindow", "Project"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page3), _translate("MainWindow", "Run"))
        self.save_project_btn.setText(_translate("MainWindow", "Project"))
        self.save_concept_btn.setText(_translate("MainWindow", "Concept"))
        self.save_role_btn.setText(_translate("MainWindow", "Role"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page4), _translate("MainWindow", "Save"))
        self.exit_btn.setText(_translate("MainWindow", "Exit"))
        self.wellcome_lbl.setText(_translate("MainWindow", "   Wellcome to MiniKrol"))
import resources_rc
